---
title: "RNAseq"
author: "Fernando Lucas Ruiz (fernando.lucas@um.es)"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    highlight: kate
    number_sections: true
    theme: spacelab
    toc: true
    toc_float: true
    code_folding: "hide"
  pdf_document:
    toc: true
subtitle: Cirugía digestiva, endocrina y trasplante de órganos abdominales (IMIB)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
```

```{r}
source("Librerias.R")
library("MatchIt")
library(uwot)
library(DESeq2)
```

# Matching algoritmo

```{r}
covs_rnaseq <- readxl::read_excel("../muestras/Muestras tejidos_RNAseq.xlsx") |> 
    dplyr::select(-T1)

covs_rnaseq$Survival <- factor(covs_rnaseq$Survival, levels = c(0,1), labels = c("YES", "NO"))
covs_rnaseq$Donación <- factor(covs_rnaseq$Donación, levels = c(0,1), labels = c("DBD", "DCD"))
covs_rnaseq$Sexo_D <- factor(covs_rnaseq$Sexo_D, levels = c(0,1), labels = c("Male", "Female"))
covs_rnaseq$HAT <- factor(covs_rnaseq$HAT, levels = c(0,1), labels = c("NO", "YES"))
covs_rnaseq$AR <- factor(covs_rnaseq$AR, levels = c(0,1), labels = c("NO", "YES"))


rownames(covs_rnaseq) <- covs_rnaseq$NHC
muestras_nombres <- covs_rnaseq$NHC 
covs_rnaseq$NHC <- NULL

```

```{r, eval=FALSE}
set.seed(1234)
covs_rnaseq <- complete(mice(covs_rnaseq, method = "rf", m = 5, maxit = 50))

saveRDS(covs_rnaseq, "../RDSs/covs_rnaseq.RDS")
```

```{r}
covs_rnaseq <- readRDS("../RDSs/covs_rnaseq.RDS")
rownames(covs_rnaseq) <- muestras_nombres
```

```{r}
m.out1 <- matchit(Survival ~ Donación + Sexo_D + Edad_D + BMI_D,
                  data = covs_rnaseq,
                  method = "optimal",
                  distance = "glm",
                  ratio = 1)

summary(m.out1, un = FALSE)
plot(m.out1, type = "jitter", interactive = F)
plot(m.out1, type = "density", interactive = FALSE,
     which.xs = ~Donación + Sexo_D + Edad_D + BMI_D)

matched <- match.data(m.out1)
rows <- rownames(matched) 

table(matched$AR)

covs_rnaseq_matched <- covs_rnaseq[rows, ] |> rownames_to_column("NHC")
# write_csv(covs_rnaseq_matched, "../Muestras tejidos_RNAseq_matched.csv")
```     

# Lectura RNAseq

```{r}
bulk_rnaseq <- read.delim("../RNAseq_24hig/Alberto_EV_FFPE_counting.tsv")

colnames(bulk_rnaseq) <- ifelse(startsWith(colnames(bulk_rnaseq), "P"),
                                paste0("DAMPS-", colnames(bulk_rnaseq)),
                                colnames(bulk_rnaseq))

genes_higado_pubmed <- readRDS("../RDSs/genes_higado_busqueda_pubmed_survival.RDS")
```

```{r}
bulk_rnaseq |>
    dplyr::select(-gene_id) |>
    pivot_longer(-gene, names_to = "Samples", values_to = "Counts") |>
    group_by(Samples) |>
    summarise(n_genes_expresados = sum(Counts > 0)) |>
    ggplot(aes(x = Samples, y = n_genes_expresados)) +
    geom_col() +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1)
    )
```

## Genes higado pubmed

```{r}
counts_matrix <- bulk_rnaseq[,-2]
counts_matrix <- counts_matrix |>
    dplyr::filter(gene %in% genes_higado_pubmed$hgnc_symbol)

rownames(counts_matrix) <- counts_matrix$gene
counts_matrix$gene <- NULL
counts_matrix <- counts_matrix |> as.matrix()

col_data <- covs_rnaseq
col_data <- col_data |>
    dplyr::filter(rownames(col_data) %in% colnames(counts_matrix))

# Asegúrate de que las columnas del conteo coincidan con las filas de col_data
all(colnames(counts_matrix) == rownames(col_data))  

setdiff(covs_rnaseq_matched$NHC, colnames(counts_matrix))
setdiff(colnames(counts_matrix), covs_rnaseq_matched$NHC)
```

```{r}
counts_matrix <- counts_matrix[, !colnames(counts_matrix) %in% c("DAMPS-P24", "DAMPS-P25", "DAMPS-P107") ]
col_data <- col_data[!rownames(col_data) %in% c("DAMPS-P24", "DAMPS-P25", "DAMPS-P107"), ]

dds <- DESeqDataSetFromMatrix(countData = counts_matrix,
                              colData = col_data,
                              design = ~ Survival) 
dds <- DESeq(dds)

res <- results(dds, contrast = c("Survival", "NO", "YES"))  # Ejemplo

resOrdered <- res[order(res$padj), ]

```

```{r}
vsd <- varianceStabilizingTransformation(dds, blind = FALSE)
metadata <- colData(vsd) |> as.data.frame() |> rownames_to_column("sample")

vsd_mat <- assay(vsd)  # Extrae la matriz transformada
vsd_t <- t(vsd_mat) 

dist_mat <- dist(vsd_t, method = "euclidean")
# PERMANOVA
perm <- adonis2(dist_mat ~ Survival, data = as.data.frame(colData(vsd)))
perm
```

```{r, fig.width=5, fig.height=5}

set.seed(1234)
umap_res <- umap(vsd_t, n_neighbors = 5, min_dist = 0.3)  # Ajusta parámetros según tus datos
umap_df <- data.frame(umap_res)
colnames(umap_df) <- c("UMAP1", "UMAP2")
umap_df$Survival <- colData(vsd)$Survival

centroids <- umap_df %>%
  dplyr::group_by(Survival) %>%
  dplyr::summarize(UMAP1 = mean(UMAP1, na.rm = TRUE),
            UMAP2 = mean(UMAP2, na.rm = TRUE))

umap_df |> rownames_to_column("sample") |>
    ggplot(aes(x = UMAP1, y = UMAP2, color = Survival)) +
    geom_point(data = centroids, size = 5, shape = 21, color = "black",
               aes(fill = Survival), show.legend = F) +
    geom_point(size = 2) +
    stat_ellipse(show.legend = F, linewidth = 0.3) +
    scale_color_manual(values = c("#87CEFA", "#FA8072")) +
    scale_fill_manual(values = c("#87CEFA", "#FA8072")) +
    annotate(geom = "text", x = 0.5, y = 4, 
             label = paste0("PERMANOVA test:\npvalue < ", perm$`Pr(>F)`[1])) +
    theme_minimal() +
    labs(title = "UMAP") +
    theme(
        plot.margin = margin(20,20,20,20),
        plot.title = element_blank(), 
        axis.ticks = element_blank(),
        axis.text = element_blank()
    ) 
```

```{r}
resOrdered |> as.data.frame() |> 
    drop_na() |>
    rownames_to_column("gene") |>
    dplyr::mutate(
        significativo = ifelse(pvalue < 0.05 & log2FoldChange > 1, 
                               "Upregulated",
                               ifelse(pvalue < 0.05 & log2FoldChange < -1,
                                      "Downregulated",
                                      "Non-significant")
                               ),
        gen = ifelse(pvalue < 0.05 & abs(log2FoldChange) > 1, gene, "")
    )|>
    ggplot(aes(x = log2FoldChange, y = -log10(pvalue), color = significativo, alpha = significativo, size = significativo)) +
    geom_point() +
    ggrepel::geom_text_repel(aes(x = log2FoldChange, y = -log10(pvalue), label = gen),
                             inherit.aes = F) +
    scale_color_manual(
        breaks = c("Upregulated", "Downregulated", "Non-significant"),
        values = c("Upregulated" = "red", "Downregulated" = "blue", "Non-significant" = "grey")
        ) +
    scale_alpha_manual(
        breaks = c("Upregulated", "Downregulated", "Non-significant"),
        values = c("Upregulated" = 1, "Downregulated" = 1, "Non-significant" = 0.5)
    ) +
    scale_size_manual(
        breaks = c("Upregulated", "Downregulated", "Non-significant"),
        values = c("Upregulated" = 3, "Downregulated" = 3, "Non-significant" = 1)
    ) +
    geom_hline(yintercept = -log10(0.05), linetype = "24", color = "grey30")+
    geom_vline(xintercept = c(-1, 1), linetype = "24", color = "grey30") +
    theme_minimal() +
    coord_fixed()
```

```{r}
p1 <- resOrdered |> as.data.frame() |> 
    drop_na() |>
    rownames_to_column("gene") |>
    dplyr::select(gene, log2FoldChange, pvalue) |>
    dplyr::filter(pvalue < 0.05 & abs(log2FoldChange) > 1) |>
    mutate(regulation = ifelse(log2FoldChange > 1, "Upregulated", "Downregulated")) |>
    bind_rows(
        data.frame(
        gene = "Non-significant genes (224)",
        log2FoldChange = 0,
        pvalue = 0,
        regulation = "Non-significant"
        )
    ) |>
    mutate(gene = fct_reorder(gene, log2FoldChange)) |>
    ggplot(aes(y=gene, x = abs(log2FoldChange), color = regulation)) +
    geom_segment(aes(y = gene, x = 0, yend = gene, xend = abs(log2FoldChange)), color = "grey20") +
    geom_point(size = 4) +
    scale_color_manual(
        breaks = c("Upregulated", "Downregulated", "Non signficant"), 
        values = c("#D5695DFF", "#5D8CA8FF", "grey")
        ) +
    theme_minimal() +
    labs(
        x = "Absolute log2 Fold change"
    ) +
    coord_fixed(ratio = 1/6)+
    theme(
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        legend.background = element_rect(color = "gray40", fill = "white",
                                     linewidth = 0.3),
        legend.margin = margin(3, 5, 3, 2),
        legend.position = "inside",
        legend.position.inside = c(0.8, 0.5),
    )
    
```

```{r}
genes_rnaseq <- resOrdered |> as.data.frame() |> 
    drop_na() |>
    rownames_to_column("gene") |>
    dplyr::select(gene, log2FoldChange, pvalue) |>
    mutate(regulation = ifelse(log2FoldChange > 1, "Upregulated", "Downregulated")) |>
    dplyr::filter(pvalue < 0.05 & abs(log2FoldChange) > 1) 
```


```{r}
dda_maaslin_prevalente <- list()

variables_salida <- c("Survival", "AR", "AHT", "Biliary_complications")

for (i in variables_salida) {

    maslin_objeto <- read_delim(paste0("../maaslin2/genus/prevalente/paper/", i, "/all_results.tsv")) %>%
    dplyr::filter(value != "RUN 1" , value != "RUN 2")

    dda_maaslin_prevalente[[i]] <- maslin_objeto
    rm(maslin_objeto)

}
```


```{r}
pubmed_query <- read.csv("../Programa genes pubtator/genes_pubmed_genus_paper.csv") |>
    filter(if_all(everything(), ~ . != "")) |>
    drop_na() |>
    dplyr::filter(!grepl("[a-z]", Gene_Name)) |>
    dplyr::filter(!Section %in% c("METHODS", "TABLE"))

taxones <- dda_maaslin_prevalente$Survival |> 
    dplyr::filter(pval < 0.05) |>
    mutate(biosis = ifelse(coef > 1, "Hiperbiosis", "Hipobiosis")) |>
    dplyr::select(feature, biosis)

pubmed_query |> 
    dplyr::filter(Variable == "Survival") |>
    dplyr::filter(Gene_Name %in% genes_rnaseq$gene) |> # pull(Taxon) |> unique()
    dplyr::filter(Gene_Name == "CCL20") 

p2 <- pubmed_query |>
    dplyr::filter(Variable == "Survival") |>
    dplyr::select(PMID, Gene_Name, Taxon) |>
    dplyr::filter(Gene_Name %in% genes_rnaseq$gene) |>
    dplyr::distinct() |>
    group_by(Gene_Name, Taxon) |>
    summarize(n = n(), .groups = "drop") |>
    arrange(desc(n)) |>
    dplyr::inner_join(genes_rnaseq, by = c("Gene_Name" = "gene")) |>
    bind_rows(
        data.frame(
        Gene_Name = "Non-significant genes (224)",
        Taxon = NA,
        n = 0,
        log2FoldChange = 0,
        pvalue = 0,
        regulation = "Non-significant"
        )
    ) |>
    mutate(Gene_Name = fct_reorder(Gene_Name, log2FoldChange)) |>
    ggplot(aes(y = Gene_Name, x = n, fill = Taxon)) +
    geom_col(width = 0.7) +
    scale_fill_manual(
        values = paletteer::paletteer_d("ggsci::default_jco"),
        breaks = c(
            "Actinobacillus",
            "Bacillus", 
            "Leptotrichia",
            "Megasphaera",
            "Neisseria",
            "Peptoniphilus_1",
            "Prevotella",
            "Sphingobium",
            "Weissella"
        )) +
    theme_minimal() +
    labs(
        x = "PMIDs"
    ) +
    coord_fixed(ratio = 6/1)+
    theme(
        axis.title.y = element_blank(),
        legend.title = element_blank()
    )

```

```{r, fig.width=10, fig.height=10}
p2a <- p2 +
    theme(
        axis.text.y = element_blank()
    )

cowplot::plot_grid(p1, p2a, ncol = 2, rel_widths = c(1, 1.2))
```


```{r, fig.width=10, fig.height=10}
plots <- list()
for (i in colnames(metadata)) {
    
    if (i %in% c("sample", "Survival", "HAT", "AR", "sizeFactor", "replaceable")){ next }
    
    if (class(metadata[[i]]) == "factor") {
        
        plots[[i]] <- metadata |>
            dplyr::select(Survival, !!sym(i)) |>
            group_by(Survival, !!sym(i)) |>
            summarize(
                value = n()
                ) |>
            ggplot(aes_string(x="Survival", y = "value", fill = i)) +
            geom_col() +
            scale_fill_manual(values = c("#87CEFA", "#FA8072")) +
            theme_minimal() +
            labs(
                y = "Count"
            ) +
            coord_fixed(ratio = 1/5) +
           theme(
               legend.position = "top",
               legend.direction = "horizontal"
               ) +
            guides(color = guide_legend(title.position = "top", title.hjust = 0.5))

    } else {
        
        plots[[i]] <-metadata |>
            dplyr::select(Survival, !!sym(i)) |>
            ggplot(aes_string(x="Survival", y = i, fill = "Survival")) +
            geom_boxplot() +
            scale_fill_manual(values = c("#87CEFA", "#FA8072")) +
            theme_minimal() +
            labs(
                y = i
            ) +
            coord_fixed(ratio = 1/5) +
            theme(
                legend.position = "none"
            )
        
        
    }
}

plots$Edad_D <- plots$Edad_D + coord_fixed(1/17)
plots$Sexo_D <- plots$Sexo_D + labs(fill = "Donor Sex")

cowplot::plot_grid(plotlist = plots, ncol = 4)
```

